---
parent: csdk
serviceName: csdk-browser-example
language: nodejs
build:
    nodejs:
        outputDistDir: test
        command: |
            mkdir test
            cp example.html test/
            cp -r webApp-plivo/public/css test/
