---
parent: csdk
serviceName: csdk-browser-example
language: nodejs
build:
    nodejs:
        outputDistDir: csdktest
        command: |
            mkdir csdktest
            cp example.html csdktest/
            cp -r webApp-plivo/public/css csdktest/
            cp -r webApp-plivo/public/img csdktest/
            cp -r webApp-plivo/public/js csdktest/
            cp -r webApp-plivo/public/lib csdktest/
