name: ReleaseCI
on:
  push:
    branches:
      - test-ghactions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release to S3
      run: bash scripts/pipeline/release.sh "plivobrowsersdk" "v2-beta-folder/example.html" ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_SECRET_ACCESS_KEY}} "example.html"
