name: ReleaseCI
on:
  push:
    branches:
      - test-ghactions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh "plivobrowsersdk" "folder1/test.txt" ${{secrets.AWS_ACCESS_KEY}} ${{secrets.AWS_SECRET_ACCESS_KEY}} "test.txt"
